### ISSUE TITLE
Is it a common practice to make one commit mixing the changes with origin codes, when forked other's repository?

### ISSUE THREAD

**Issue by PsiACE** [dataslime/ritelinked#6]
ref: https://github.com/datafuselabs/databend/issues/3979

Hi @wangzhen11aaa , this question is about ritelinked, and I think we can open an issue at https://github.com/dataslime/ritelinked .

---

I'm glad you're interested in ritelinked. ritelinked is derived from hashlink and they share most of the code logic. The main differences are these:

- some new features, such as `amortized`, support `no_std`
- better maintenance and well organization (eg. ritelinked's `serde` module was fixed earlier than hashlink)
- some functions such as `get_refresh`, `retain`

see old commit history: https://github.com/dataslime/ritelinked/commits/ritelabs/ritelinked

Also, it is a fact that ritelinked is pretty much my personal hashlink fork, although it is used by some projects. Since I plan to do some rewrites, I overwrite the commit records under the main branch, sorry for the confusion.

**Comment by PsiACE** [comment]
So back to the question, I don't think the behavior of ritelinked is a common practice.

**Comment by wangzhen11aaa** [comment]
That's Excellent
